navsat_transform:
  ros__parameters:
    frequency: 30.0
    delay: 0
    magnetic_declination_radians: 0.0429351  # For lat/long 55.944831, -3.186998
    yaw_offset: 0 #Would be offset if the odom was not at 0 pointing east
    zero_altitude: true
    broadcast_utm_transform: true
    publish_filtered_gps: true
    use_odometry_yaw: false
    wait_for_datum: false
