# http://wiki.ros.org/costmap_2d#costmap_2d.2BAC8-layered.Parameters
global_costmap:
  global_frame: map
  robot_base_frame: base_footprint
  transform_tolerance: 0.5  #was 0.2
  update_frequency: 1 #was 1
  publish_frequency: 1 #was 1, really just the visual aspect does not need to be published for move base to read
  rolling_window: false
  always_send_full_costmap: true #was false

  resolution: 0.05  #was 0.5 
  width: 20
  height: 20
  origin_x: -20.0
  origin_y: -20.0

  plugins:
    - {name: static_layer,      type: "costmap_2d::StaticLayer"}
    - {name: obstacle_layer,    type: "costmap_2d::ObstacleLayer"}
    - {name: inflation_layer,   type: "costmap_2d::InflationLayer"}
