# http://wiki.ros.org/costmap_2d#costmap_2d.2BAC8-layered.Parameters
local_costmap:
  global_frame: map
  robot_base_frame: base_footprint
  transform_tolerance: 0.5
  update_frequency: 0.5
  publish_frequency: 0.5
  rolling_window: true
  always_send_full_costmap: true #was false

  resolution: 0.05
  width: 10
  height: 10
  
  # added params for Panther
  inscribed_radius: 0.323875
  circumscribed_radius: 0.560129

  plugins: 
    - {name: obstacle_layer,    type: "costmap_2d::ObstacleLayer"}
    - {name: inflation_layer,   type: "costmap_2d::InflationLayer"}
