# http://wiki.ros.org/move_base#Parameters

# General parameters
controller_frequency: 20 # was 10
planner_patience: 5.0
controller_patience: 15.0
shutdown_costmaps: false
oscillation_timeout: 0.0
oscillation_distance: 0.5
planner_frequency: 0
max_planning_retries: -1

# Planner plugins
base_global_planner: global_planner/GlobalPlanner
base_local_planner: base_local_planner/TrajectoryPlannerROS

# Recovery behavior parameters
recovery_behavior_enabled: true
clearing_rotation_allowed: true # was true, false good for debugging local planner
conservative_reset_dist: 2.0
