# http://wiki.ros.org/base_local_planner#Parameters
TrajectoryPlannerROS:

  # Robot configuration
  acc_lim_x: 8 #leo was 0.5, default 2.5
  acc_lim_theta: 8 #leo was 2, default 2.5
  max_vel_x: 2 # was 0.5
  min_vel_x: 0.6 # was 0.5
  max_vel_theta: 2.5 # was 0.5
  min_vel_theta: -2.5 # was -0.5
  min_in_place_vel_theta: 2 # was 0.4
  escape_vel: -2 # was -0.1
  holonomic_robot: false

  # Goal tolerance
  yaw_goal_tolerance: 3 # was 0.1
  xy_goal_tolerance: 0.2  # was 0.2
  latch_xy_goal_tolerance: false # was true

  # Forward simulation
  sim_time: 4.2 # was 3.0
  sim_granularity: 0.05
  angular_sim_granularity: 0.025 # was 0.025
  vx_samples: 20
  vtheta_samples: 40 # was 20

  # Trajectory scoring
  meter_scoring: true
  path_distance_bias: 3.2 #2if this is the same as pdist_scale, weigt for how much controller should stay to path, was 0.5
  goal_distance_bias: 0.5 #was 0.3
  occdist_scale: 0.014 # was 0.005 sets fear of colisions, higher more fear
  heading_lookahead: 0.325
  heading_scoring: true # was false
  heading_scoring_timestep: 0.8
  dwa: true
  publish_cost_grid_pc: true #default false 
  global_frame_id: odom

  # Oscillation
  oscillation_reset_dist: 0.04 # was 0.05

  # Global plan
  prune_plan: true
