# http://wiki.ros.org/base_local_planner#Parameters
TrajectoryPlannerROS:

  # Robot configuration
  acc_lim_x: 6 #leo was 0.5,
  acc_lim_theta: 6 #leo was 2, 
  max_vel_x: 2
  min_vel_x: 0.5 
  max_vel_theta: 1.2 # was 0.5 #1.2
  min_vel_theta: -1.2 # was -0.5
  min_in_place_vel_theta: 0.6
  escape_vel: -1 # was -0.1
  holonomic_robot: false

  # Goal tolerance
  yaw_goal_tolerance: 0.1 # was 0.1
  xy_goal_tolerance: 0.46  # was 0.2
  latch_xy_goal_tolerance: true # was true

  # Forward simulation
  sim_time: 1 # was 4.2
  sim_granularity: 0.025 #was 0.05
  angular_sim_granularity: 0.025 
  vx_samples: 3 # was 20
  vtheta_samples: 20

  # Trajectory scoring
  meter_scoring: true
  path_distance_bias: 0.6 #2if this is the same as pdist_scale, weigt for how much controller should stay to path, was 0.5
  goal_distance_bias: 0.8 #was 0.3
  occdist_scale: 0.01 # was 0.005 sets fear of colisions, higher more fear, #0.014
  heading_lookahead: 0.325
  heading_scoring: true # was false
  heading_scoring_timestep: 0.8
  dwa: true
  publish_cost_grid_pc: true #default false 
  global_frame_id: odom

  # Oscillation
  oscillation_reset_dist: 0.04 # was 0.05

  # Global plan
  prune_plan: true
