// Generated by gencpp from file sdr_control/SwitchVelocity.msg
// DO NOT EDIT!


#ifndef SDR_CONTROL_MESSAGE_SWITCHVELOCITY_H
#define SDR_CONTROL_MESSAGE_SWITCHVELOCITY_H

#include <ros/service_traits.h>


#include <sdr_control/SwitchVelocityRequest.h>
#include <sdr_control/SwitchVelocityResponse.h>


namespace sdr_control
{

struct SwitchVelocity
{

typedef SwitchVelocityRequest Request;
typedef SwitchVelocityResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SwitchVelocity
} // namespace sdr_control


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::sdr_control::SwitchVelocity > {
  static const char* value()
  {
    return "d1597f0c930b70b3b5b1b67db31b5f98";
  }

  static const char* value(const ::sdr_control::SwitchVelocity&) { return value(); }
};

template<>
struct DataType< ::sdr_control::SwitchVelocity > {
  static const char* value()
  {
    return "sdr_control/SwitchVelocity";
  }

  static const char* value(const ::sdr_control::SwitchVelocity&) { return value(); }
};


// service_traits::MD5Sum< ::sdr_control::SwitchVelocityRequest> should match
// service_traits::MD5Sum< ::sdr_control::SwitchVelocity >
template<>
struct MD5Sum< ::sdr_control::SwitchVelocityRequest>
{
  static const char* value()
  {
    return MD5Sum< ::sdr_control::SwitchVelocity >::value();
  }
  static const char* value(const ::sdr_control::SwitchVelocityRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::sdr_control::SwitchVelocityRequest> should match
// service_traits::DataType< ::sdr_control::SwitchVelocity >
template<>
struct DataType< ::sdr_control::SwitchVelocityRequest>
{
  static const char* value()
  {
    return DataType< ::sdr_control::SwitchVelocity >::value();
  }
  static const char* value(const ::sdr_control::SwitchVelocityRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::sdr_control::SwitchVelocityResponse> should match
// service_traits::MD5Sum< ::sdr_control::SwitchVelocity >
template<>
struct MD5Sum< ::sdr_control::SwitchVelocityResponse>
{
  static const char* value()
  {
    return MD5Sum< ::sdr_control::SwitchVelocity >::value();
  }
  static const char* value(const ::sdr_control::SwitchVelocityResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::sdr_control::SwitchVelocityResponse> should match
// service_traits::DataType< ::sdr_control::SwitchVelocity >
template<>
struct DataType< ::sdr_control::SwitchVelocityResponse>
{
  static const char* value()
  {
    return DataType< ::sdr_control::SwitchVelocity >::value();
  }
  static const char* value(const ::sdr_control::SwitchVelocityResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SDR_CONTROL_MESSAGE_SWITCHVELOCITY_H
