// Generated by gencpp from file sdr_control/SwitchVelocityRequest.msg
// DO NOT EDIT!


#ifndef SDR_CONTROL_MESSAGE_SWITCHVELOCITYREQUEST_H
#define SDR_CONTROL_MESSAGE_SWITCHVELOCITYREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace sdr_control
{
template <class ContainerAllocator>
struct SwitchVelocityRequest_
{
  typedef SwitchVelocityRequest_<ContainerAllocator> Type;

  SwitchVelocityRequest_()
    : switch_to()  {
    }
  SwitchVelocityRequest_(const ContainerAllocator& _alloc)
    : switch_to(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _switch_to_type;
  _switch_to_type switch_to;





  typedef boost::shared_ptr< ::sdr_control::SwitchVelocityRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sdr_control::SwitchVelocityRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SwitchVelocityRequest_

typedef ::sdr_control::SwitchVelocityRequest_<std::allocator<void> > SwitchVelocityRequest;

typedef boost::shared_ptr< ::sdr_control::SwitchVelocityRequest > SwitchVelocityRequestPtr;
typedef boost::shared_ptr< ::sdr_control::SwitchVelocityRequest const> SwitchVelocityRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sdr_control::SwitchVelocityRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sdr_control::SwitchVelocityRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::sdr_control::SwitchVelocityRequest_<ContainerAllocator1> & lhs, const ::sdr_control::SwitchVelocityRequest_<ContainerAllocator2> & rhs)
{
  return lhs.switch_to == rhs.switch_to;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::sdr_control::SwitchVelocityRequest_<ContainerAllocator1> & lhs, const ::sdr_control::SwitchVelocityRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace sdr_control

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::sdr_control::SwitchVelocityRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sdr_control::SwitchVelocityRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sdr_control::SwitchVelocityRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sdr_control::SwitchVelocityRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sdr_control::SwitchVelocityRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sdr_control::SwitchVelocityRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sdr_control::SwitchVelocityRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a0f6f703ab04720d3a56cd69b01080bd";
  }

  static const char* value(const ::sdr_control::SwitchVelocityRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa0f6f703ab04720dULL;
  static const uint64_t static_value2 = 0x3a56cd69b01080bdULL;
};

template<class ContainerAllocator>
struct DataType< ::sdr_control::SwitchVelocityRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sdr_control/SwitchVelocityRequest";
  }

  static const char* value(const ::sdr_control::SwitchVelocityRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sdr_control::SwitchVelocityRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string switch_to\n"
;
  }

  static const char* value(const ::sdr_control::SwitchVelocityRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sdr_control::SwitchVelocityRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.switch_to);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SwitchVelocityRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sdr_control::SwitchVelocityRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sdr_control::SwitchVelocityRequest_<ContainerAllocator>& v)
  {
    s << indent << "switch_to: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.switch_to);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SDR_CONTROL_MESSAGE_SWITCHVELOCITYREQUEST_H
